#ifndef THEME_H
#define THEME_H
#include <stdint.h>

#define COLOR_SKY_TOP      0xFF87CEEB
#define COLOR_SKY_HORIZON  0xFFFFF0D6
#define COLOR_CLOUD_WHITE  0xFFFFFAF0
#define COLOR_CLOUD_SHADOW 0xFFE8E8F0
#define COLOR_GRASS_LIGHT  0xFF90EE90
#define COLOR_GRASS_DARK   0xFF228B22
#define COLOR_WINDOW_BG    0xFFFFF8F0
#define COLOR_WINDOW_BORDER 0xFFD2B48C
#define COLOR_ACCENT_PINK  0xFFFFB7C5
#define COLOR_ACCENT_SAGE  0xFF9DC183
#define COLOR_TEXT_DARK    0xFF3D2B1F
#define COLOR_TEXT_MEDIUM  0xFF6B4F3A
#define COLOR_TASKBAR_BG   0xFFFFF8F0
#define COLOR_TRANSPARENT  0x00000000

#endif
